---
- name: Setup kubeconfig on worker node
  hosts: pi2
  become: true
  gather_facts: true
  vars:
    k3s_yaml: '{{ lookup(''file'', ''/etc/rancher/k3s/k3s.yaml'') }}'
  tasks:
    - name: Create .kube directory
      file:
        path: /home/butler/.kube
        state: directory
        mode: "0755"
        owner: butler
    - name: Copy k3s.yaml to user's home
      copy:
        content: '{{ k3s_yaml | replace(''127.0.0.1'', ''192.168.5.253'') }}'
        dest: /home/butler/.kube/config
        owner: brandonapol
        mode: "0600"
