name: Build
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  autobutler-build:
    runs-on: ubuntu-latest
    outputs:
      run-id: ${{ github.run_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Setup sqlc
        uses: ./.github/actions/setup-sqlc
      - name: Setup Templ
        uses: ./.github/actions/setup-templ
      - name: Build
        run: |
          make build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/autobutler
          if-no-files-found: error
  autobutler-build-test:
    uses: ./.github/workflows/autobutler-test.yml
    needs:
      - autobutler-build
    with:
      is-remote: false
      run-id: ${{ needs.autobutler-build.outputs.run-id }}

