name: Backend Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
env:
  WORKING_DIR: ${{ github.workspace }}/src/autobutler/backend
defaults:
  run:
    shell: bash
jobs:
  backend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: go mod download
      - name: Build
        working-directory: ${{ env.WORKING_DIR }}
        run: make build
      - name: Build [linux/arm64]
        working-directory: ${{ env.WORKING_DIR }}
        run: make build/linux/arm64
      - name: Build [mac/arm64]
        working-directory: ${{ env.WORKING_DIR }}
        run: make build/mac/arm64
      - name: Build [windows/amd64]
        working-directory: ${{ env.WORKING_DIR }}
        run: make build/windows/amd64
      - name: Build [windows/arm64]
        working-directory: ${{ env.WORKING_DIR }}
        run: make build/windows/arm64
