name: Backend Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      image-tag:
        description: Image tag to run
        type: string
env:
  WORKING_DIR: ${{ github.workspace }}/src/autobutler/backend
  GOFLAGS: -buildvcs=false
defaults:
  run:
    shell: bash
jobs:
  backend-build:
    runs-on: ubuntu-latest
    container:
      image: exokomodo/exoflow-devcontainer:${{ inputs.image-tag || (github.event_name == 'pull_request' && 'latest') || (github.head_ref || github.ref_name) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: go mod download
      - name: Build
        working-directory: ${{ env.WORKING_DIR }}
        run: make build
