name: Devcontainer (build and push)
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      as-latest:
        description: Push as the latest tag
        type: boolean
        required: false
        default: false
env:
  TAGS: ${{ github.repository }}-devcontainer:${{ github.head_ref || github.ref_name }}${{ (github.ref == 'refs/heads/main' || inputs.as-latest) && format(',{0}-devcontainer:latest', github.repository) || ''}}
jobs:
  devcontainer:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platforms:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Print env
        run: |
          echo ${{ env.TAGS }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: exokomodo
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ matrix.platforms }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.TAGS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  pass:
    name: Pass?
    runs-on: ubuntu-latest
    if: always()
    needs:
      - devcontainer
    env:
      RESULT: ${{ needs.devcontainer.result }}
    steps:
      - name: Pass
        if: ${{ env.RESULT != 'failure' }}
        run: |
          echo "[PASS] Linting" >> ${GITHUB_STEP_SUMMARY}
      - name: Fail
        if: ${{ env.RESULT == 'failure' }}
        run: |
          echo "[FAIL] Linting" >> ${GITHUB_STEP_SUMMARY}
