name: dotai - CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      image-tag:
        description: Image tag to run
        type: string
env:
  WORKING_DIR: ${{ github.workspace }}/src/dotai/ui
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: exokomodo/exoflow-devcontainer:${{ inputs.image-tag || (github.event_name == 'pull_request' && 'latest') || (github.head_ref || github.ref_name) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install node-gyp
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          bun install node-gyp
      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          bun install
      - name: Build
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          bun run build
      - name: Generate
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          bun run generate
