name: autobutler.ai - CD
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  dotai-cd:
    name: autobutler.ai - Trigger Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Dispatch
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.FG_PAT }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: 'autobutler-ai',
              repo: 'autobutler.ai',
              workflow_id: 'deploy.yml',
              ref: 'main',
              inputs: {
                ref: context.ref
              }
            });
