name: dotai - CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      image-tag:
        description: Image tag to run
        type: string
env:
  WORKING_DIR: ${{ github.workspace }}/src/dotai/ui
defaults:
  run:
    shell: bash
jobs:
  dotai-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
      - name: Install node-gyp
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          bun install node-gyp
      - name: Install dependencies
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          bun install
      - name: Build
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          bun run build
      - name: Generate
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          bun run generate
